---
- name: Install caffe and python
  homebrew:
    name: ['caffe', 'python', 'zlib', 'pyenv']
    state: latest

- name: Install zlib at os level
  become: yes
  command: installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
  ignore_errors: yes

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: latest

