---
- name: Download git repo
  git:
    repo: https://github.com/RadeonOpenCompute/llvm-project.git
    dest: ~/repos/llvm-project
    version: roc-4.0.x

- name: Create build project
  file:
    path: ~/repos/llvm-project/build
    state: directory

- name: Cmake hip compiler
  shell: cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" ../llvm
  args:
    chdir: ~/repos/llvm-project/build

- name: Make project
  community.general.make:
    chdir: ~/repos/llvm-project/build
    params:
      NUM_THREADS: 4

- name: Install llvm
  community.general.make:
    chdir: ~/repos/llvm-project/build
    target: install
  become: yes
