---
- name: Setup laptop
  hosts: local
  remote_user: salvarez
  become: no

  roles:
    - macos
    - macos-opt
    - vim
    - spacemacs
    - zsh
    - { role: ml, tags: ['ml'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: set-java-8, tags: ['java'] }

