---
- name: Install nvidia-docker apt key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
  become: yes

- name: Install nvidia-docker repo
  get_url:
    url: https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  become: yes

- name: Install nvidia
  apt:
    update_cache: yes
    pkg:
      - nvidia-driver-450
      - nvidia-cuda-toolkit
      - nvidia-container-runtime
      - nvidia-container-toolkit
  register: nvidia_install
  become: yes

