---
- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  ignore_errors: yes
  become: yes

- name: Install packages
  shell: brew install node restic gnu-tar inetutils the_silver_searcher zsh zsh-completions zsh-autosuggestions tmux mosh wget leiningen mas git-lfs

- name: Add zsh to /etc/shells
  become: yes
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'

- name: Change shell
  become_user: root
  command: "chsh -s /usr/local/bin/zsh {{ lookup('env','USER') }}"

- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Tap emacs-plus
  homebrew_tap:
    name: d12frosted/emacs-plus
    state: present

- name: Tap versions
  homebrew_tap:
    name: caskroom/versions
    state: absent

- name: Install emacs-plus
  shell: brew install emacs-plus

- name: Link emacs-plus
  homebrew:
    name: ['emacs-plus']
    state: linked

- name: Install casks
  shell: brew cask install displaycal viscosity jumpcut slack istat-menus caffeine discord docker hyper font-fira-code vagrant firefox papers amethyst battle-net sensiblesidebuttons dropbox nextcloud

- name: Tap versions
  homebrew_tap:
    name: AdoptOpenJDK/openjdk
    state: present

- name: Install Java 8
  shell: brew cask install adoptopenjdk/openjdk/adoptopenjdk8

- name: Install pip
  shell: easy_install pip
  become: yes

- name: Install trello
  shell: mas install 1278508951

- name: Install rocketchat
  shell: mas install 1086818840

- name: Copy hyper.js config
  template:
    src: hyper.js
    dest: ~/.hyper.js

- name: Fix key repeat in hyper
  shell: defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false

- name: Show status bar in Safari
  shell: defaults write com.apple.Safari ShowStatusBar -boolean true

- name: Show status bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true
