---
- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  ignore_errors: yes
  become: yes

- name: Install packages
  homebrew:
    name: ['node', 'restic', 'gnu-tar', 'inetutils', 'the_silver_searcher', 'zsh', 'zsh-completions', 'zsh-autosuggestions', 'tmux', 'mosh', 'wget', 'leiningen', 'mas', 'git-lfs']
    state: latest

- name: Add zsh to /etc/shells
  become: yes
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'

- name: Change shell
  become_user: root
  command: "chsh -s /usr/local/bin/zsh {{ lookup('env','USER') }}"

- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Tap versions
  homebrew_tap:
    name: caskroom/versions
    state: absent

- name: Install casks
  homebrew_cask:
    name: ['displaycal', 'viscosity', 'jumpcut', 'slack', 'istat-menus', 'caffeine', 'java', 'discord', 'docker', 'hyper', 'font-fira-code', 'virtualbox', 'vagrant', 'firefox', 'emacs', 'papers', 'amethyst', 'battle-net', 'sensiblesidebuttons']
    state: latest

- name: Install casks without quarantine
  homebrew_cask:
    name: ['dropbox']
    state: latest
    install_options: no_quarantine

- name: Tap versions
  homebrew_tap:
    name: AdoptOpenJDK/openjdk
    state: present

- name: Install Java 8
  homebrew_cask:
    name: ['adoptopenjdk8']
    state: latest

- name: Install pip
  shell: easy_install pip
  become: yes

- name: Install trello
  shell: mas install 1278508951

- name: Copy hyper.js config
  template:
    src: hyper.js
    dest: ~/.hyper.js

- name: Fix key repeat in hyper
  shell: defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false

- name: Show status bar in Safari
  shell: defaults write com.apple.Safari ShowStatusBar -boolean true

- name: Show status bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true
