---
- name: Download spacemacs repo
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
    version: develop

- name: Copy spacemacs config
  template:
    src: spacemacs
    dest: ~/.spacemacs
