---
- name: Install repo
  become: yes
  apt_repository:
    repo: ppa:kelleyk/emacs

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - openjdk-8-jdk
    - rake
    - git
    - zsh
    - vim
    - ranger
    - emacs26
    - x11-xkb-utils
    - libssl-dev
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - apt-transport-https
    - gnupg2

- name: Install python packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip
    - python3-virtualenv
    - virtualenvwrapper

- name: Add kubectl apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: yes

- name: Add kubectl repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  become: yes

- name: Install kubectl
  package:
    name: kubectl
  become: yes

- name: Add helm apt key
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
  become: yes

- name: Add helm repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
  become: yes

- name: Install helm
  package:
    name: helm
  become: yes

- name: Install python modules
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Download doctl
  get_url:
    url: https://github.com/digitalocean/doctl/releases/download/v1.46.0/doctl-1.46.0-linux-amd64.tar.gz
    dest: /tmp/doctl.tar.gz

- name: Uncompress doctl
  unarchive:
    src: /tmp/doctl.tar.gz
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  become: yes
