---
- name: Install repo
  become: yes
  apt_repository:
    repo: ppa:kelleyk/emacs

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - openjdk-8-jdk
    - rake
    - git
    - zsh
    - vim
    - ranger
    - emacs26
    - x11-xkb-utils
    - nodejs-dev
    - node-gyp
    - libssl1.0-dev
    - npm
    - nodejs
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev

- name: Install python packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip
    - python-pip
    - python-virtualenv
    - virtualenvwrapper

- name: Install python modules
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Install i3 packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - autoconf
    - automake
    - compton
    - feh
    - fonts-firacode
    - fonts-materialdesignicons-webfont
    - hsetroot
    - i3
    - libev-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libxcb-cursor-dev
    - libxcb-icccm4-dev
    - libxcb-keysyms1-dev
    - libxcb-randr0-dev
    - libxcb-shape0-dev
    - libxcb-util0-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-xrm0
    - libxcb1-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libyajl-dev
    - python-pip
    - python3-pip
    - rofi
    - rxvt-unicode
    - scrot
    - x11-xserver-utils
    - xautolock

- name: Create bin folder
  file:
    path: ~/bin/
    state: directory

- name: Install tdrop
  get_url:
    url: https://raw.githubusercontent.com/noctuid/tdrop/master/tdrop
    dest: ~/bin/tdrop
    mode: 0755

- name: Install bartermapp
  template:
    src: bartermapp
    dest: ~/bin/bartermapp
    mode: 0755

- name: Install random-string
  template:
    src: random-string
    dest: ~/bin/random-string
    mode: 0755

- name: Create i3 config folder
  file:
    path: ~/.config/i3/
    state: directory

- name: Create rofi config folder
  file:
    path: ~/.config/rofi/
    state: directory

- name: Create alacritty config folder
  file:
    path: ~/.config/alacritty/
    state: directory

- name: Create polybar config folder
  file:
    path: ~/.config/polybar/
    state: directory

- name: Copy i3 config
  template:
    src: i3_config
    dest: ~/.config/i3/config

- name: Copy rofi config
  template:
    src: rofi_config
    dest: ~/.config/rofi/config

- name: Copy rofi color theme
  template:
    src: andrea.rasi
    dest: ~/.config/rofi/andrea.rasi

- name: Copy lock script
  template:
    src: fuzzy_lock.sh
    dest: ~/.config/i3/fuzzy_lock.sh
    mode: 0755

- name: Copy alacritty config
  template:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml

- name: Copy polybar config
  template:
    src: polybar_config
    dest: ~/.config/polybar/config

- name: Clone i3 gaps
  git:
    repo: https://www.github.com/Airblader/i3
    dest: ~/repos/i3-gaps

- name: Autoreconf i3 gaps
  shell: autoreconf --force --install
  args:
    chdir: ~/repos/i3-gaps

- name: Create build dir for i3 gaps
  file:
    path: ~/repos/i3-gaps/build
    state: directory

- name: Configure i3 gaps
  shell: ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
  args:
    chdir: ~/repos/i3-gaps/build

- name: Make i3 gaps
  shell: make
  args:
    chdir: ~/repos/i3-gaps/build

- name: Install i3 gaps
  shell: make install
  become: yes
  args:
    chdir: "/home/{{ lookup('env','USER') }}/repos/i3-gaps/build"

- name: Create scripts folder
  file:
    path: ~/.scripts
    state: directory

- name: Copy walternate script
  template:
    src: walternate
    dest: ~/.scripts/walternate
    mode: 0755

- name: Copy polylaunch script
  template:
    src: polylaunch
    dest: ~/.scripts/polylaunch
    mode: 0755

- name: Copy Xresources
  template:
    src: Xresources
    dest: ~/.Xresources

- name: i3 python deps
  pip:
    name: ephem
    state: latest

- name: Install polybar packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - cmake
    - cmake-data
    - pkg-config
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - libxcb-composite0-dev
    - python-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libcurl4-openssl-dev
    - libnl-genl-3-dev

- name: Clone polybar
  git:
    repo: https://github.com/jaagr/polybar
    dest: ~/repos/polybar
    version: 3.3

- name: Create polybar build folder
  file:
    path: ~/repos/polybar/build
    state: directory

- name: Make polybar
  shell: cmake ..
  args:
    chdir: ~/repos/polybar/build

- name: Install polybar
  shell: make install
  become: yes
  args:
    chdir: "/home/{{ lookup('env','USER') }}/repos/polybar/build"

- name: Install alacritty packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip
    - cargo

- name: Download alacritty
  get_url:
    url: https://github.com/jwilm/alacritty/releases/download/v0.2.4/Alacritty-v0.2.4_amd64.deb
    dest: /tmp/alacritty.deb

- name: Install alacritty
  apt:
    deb: /tmp/alacritty.deb
  become: yes

- name: Create wallpapers folder
  file:
    path: ~/.config/wallpapers/
    state: directory

- name: Download wallpapers
  get_url:
    url: "{{ item }}"
    dest: ~/.config/wallpapers/mojave-night.jpg
  with_items:
    - "https://9to5mac.com/wp-content/uploads/sites/6/2018/06/mojave-night.jpg"

- name: Connect to windows daemon
  lineinfile:
    path: ~/.zshrc
    state: present
    line: "export DOCKER_HOST=tcp://localhost:2375"
