---
- name: Install caffe and python
  homebrew:
    name: ['caffe', 'python', 'zlib', 'pyenv', 'xz']
    state: latest

- name: Install zlib at os level
  become: yes
  command: installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
  ignore_errors: yes

- name: Install python 3.7.4
  shell: SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/ pyenv install 3.7.4
  ignore_errors: yes

- shell: brew reinstall python

- shell: pip3 install --upgrade pip
  become: yes

- name: Install virtualenv
  pip:
    executable: pip3
    name: virtualenv
    state: latest
  become: yes

- name: Install virtualenvwrapper
  pip:
    executable: pip3
    name: virtualenvwrapper
    state: latest
  become: yes

