---
- name: Install docker dependencies
  package:
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  become: yes

- name: Install docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Assign permissions to client
  shell: usermod -aG docker "`whoami`"
  become: yes
