---
- gem:
    name: rake

- name: Download janus
  get_url:
    url: https://raw.githubusercontent.com/carlhuda/janus/master/bootstrap.sh
    dest: /tmp/janus-bootstrap.sh
    mode: 0755

- name: Install janus
  shell: bash /tmp/janus-bootstrap.sh

- name: Install vimrc.after
  template:
    src: vimrc.after
    dest: ~/.vimrc.after

