---
- name: Tap dive
  homebrew_tap:
    name: wagoodman/dive
    state: present

- name: Install opt apps
  homebrew:
    name: ['minio/stable/mc', 'handbrake', 'dive', 'exiftool']

- name: Install opt casks
  homebrew_cask:
    name: ['gog-galaxy', 'grandperspective', 'vlc', 'htop', 'clion', 'pycharm', 'steam', 'postman']

- name: Install Keynote
  shell: mas install 409183694

- name: Install Numbers
  shell: mas install 409203825

- name: Install Pages
  shell: mas install 409201541

- name: Install Xcode
  shell: mas install 497799835

- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  become: yes

- name: Install RDP Client
  shell: mas install 1295203466
