---
- name: Tap dive
  homebrew_tap:
    name: wagoodman/dive
    state: present

- name: Install opt apps
  homebrew:
    name: ['minio/stable/mc', 'handbrake', 'dive', 'exiftool', 'htop', 'yarn', 'gnupg', 'postgresql']

- name: Install rvm keys
  shell: gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: Install opt casks
  homebrew_cask:
    name: ['mactex-no-gui', 'balenaetcher', 'intel-power-gadget', 'softraid', 'sensiblesidebuttons', 'gog-galaxy', 'grandperspective', 'vlc', 'clion', 'pycharm', 'steam', 'postman']

- name: Install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby=jruby --gems=rails,puma
  become: no

- name: Install Keynote
  shell: mas install 409183694

- name: Install Numbers
  shell: mas install 409203825

- name: Install Pages
  shell: mas install 409201541

- name: Install Xcode
  shell: mas install 497799835

- name: Link to xcode
  shell: xcode-select -s /Applications/Xcode.app/Contents/Developer
  become: yes

- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  become: yes

- name: Install RDP Client
  shell: mas install 1295203466
